### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by Pikachupikachup** [Hongtae/SwiftVVD#14]
How do you open this on swift playgrounds for iPadOS? I don’t have a computer but I really wanna try this, it seem cool!

**Comment by Hongtae** [comment]
I don't have any experience with Swift-Playground, so I can't say for sure, but I don't think it will build easily. To build it, you need SwiftPM, which is included in the Swift package. On Mac, it's included in Xcode, and on Windows, you can get it by installing the Swift 5.8 installer.
I'll try to test it with Swift-Playgound in the near future, but it's still in the early stages of development, so there are a lot of unimplemented features. Thanks for your interest.

**Comment by Pikachupikachup** [comment]
Ok, I'm not gonna be creating any real games with it probably, but it seems like a really cool idea! I think when you make 1.0, it's gonna be great! Also, if you have a Mac, you can get swift playgrounds for that too.

**Comment by Pikachupikachup** [comment]
Also, maybe you could publish a .playground or .playgroundbook for access, because I use those things all the time(https://github.com/uraimo/Awesome-Swift-Playgrounds for where I find the playgrounds) and they work if I try some things with them.

**Comment by Pikachupikachup** [comment]
This is something called arena: https://github.com/finestructure/Arena . It seems like it might be able to help you if you decide to make a swift playground version, but I don’t know because I don’t have a mac(actually I have one, but it’s really, REALLY OLD) and I haven’t tried using one so I don’t know if this is just a startup, but doesn’t include any code.

**Comment by Pikachupikachup** [comment]
I checked it out, and if you publish a release(just source code), you might be able to use swift packages to open it

**Comment by Hongtae** [comment]
I'll keep this in mind when I release a new version and try to make it available in Swift-Playground as well. Thanks for the great information. 
I'm going to close this issue now, but if you have any other suggestions or questions, I'd love to hear from you.
